language: generic
sudo: required
services:
  - docker
cache:
  directories:
    - "$HOME/google-cloud-sdk/"
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service-account.json.enc -out service-account.json -d
  - gcloud version || true
  - echo "Installing google-cloud-sdk" && if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf "$HOME/google-cloud-sdk"; curl https://sdk.cloud.google.com | bash 2>/dev/null >/dev/null; fi
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project multi-k8s-248608
  - gcloud config set compute/zone us-central1-a
  - gcloud container clusters get-credentials standard-cluster-1
  # Log in to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  - docker build -t sanjaypsachdev/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sanjaypsachdev/react-test yarn test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master