sudo: required
services:
  - docker
cache:
  directories:
    - "$HOME/google-cloud-sdk/"
before_install:
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service-account.json.enc -out service-account.json -d
  - export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project multi-k8s-248608
  - gcloud config set compute/zone us-central1-a
  - gcloud container clusters get-credentials standard-cluster-1

script:
  - docker run -e CI=true sanjaypsachdev/docker-react npm run test