apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: client
          image: sanjaypsachdev/multi-client:latest
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 1
              memory: 1Gi
          ports:
            - containerPort: 3000